const KEY="nexaro-crm-v1-1";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const uid=()=>crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const today=()=>new Date().toISOString().slice(0,10);
const money=n=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n)||0);
const base={leads:[],tasks:[],quotes:[],invoices:[],settings:{}};
let S=(()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return {...base,...x,leads:x.leads||[],tasks:x.tasks||[],quotes:x.quotes||[],invoices:x.invoices||[],settings:x.settings||{}}}catch{return structuredClone(base)}})();
let lf="all",tf="open",area=null,route=[];
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1900)};
const close=id=>$("#"+id)?.close(), open=id=>$("#"+id)?.showModal();
function qual(t){t=+t||0;return t>=15000?{l:"A",x:"Sehr starkes Potenzial",c:"qual-A"}:t>=10000?{l:"B",x:"Stark qualifiziert",c:"qual-B"}:t>=5000?{l:"C",x:"Qualifiziert",c:"qual-C"}:{l:"D",x:"Unter internem Vertriebsziel",c:"qual-D"}}
const sl=s=>({neu:"Neu",kontaktiert:"Kontaktiert",termin:"Termin",angebot:"Angebot",gewonnen:"Gewonnen",verloren:"Verloren"}[s]||s);
function nav(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));window.scrollTo(0,0);render()}
$$('[data-screen]').forEach(b=>b.onclick=()=>nav(b.dataset.screen));
document.onclick=e=>{const c=e.target.closest('[data-close]');if(c){close(c.dataset.close);return}const a=e.target.closest('[data-action]')?.dataset.action;if(a)act(a)};
function act(a){if(a==='new-lead')return lead();if(a==='new-task')return task();if(a==='pricing')return pricing();if(a==='commission')return commission();if(a==='new-quote')return quote();if(a==='new-invoice')return invoice();if(a==='export-csv')return csv();if(a==='backup')return download('nexaro-crm-backup.json',JSON.stringify(S,null,2),'application/json');if(a==='restore')return $('#restoreInput').click();if(a==='demo')return demo();if(a==='clear'&&confirm('Alle lokalen CRM-Daten löschen?')){S=structuredClone(base);save();render();toast('CRM gelöscht')}}
function lead(id=null){$('#leadForm').reset();$('#leadId').value=id||'';$('#leadDialogTitle').textContent=id?'Lead bearbeiten':'Neuer Lead';const l=id&&S.leads.find(x=>x.id===id);if(l){for(const [k,i] of Object.entries({company:'fCompany',industry:'fIndustry',status:'fStatus',contact:'fContact',phone:'fPhone',email:'fEmail',address:'fAddress',tpv:'fTpv',provider:'fProvider',terminal:'fTerminal',product:'fProduct',priority:'fPriority',need:'fNeed',next:'fNext',due:'fDue',notes:'fNotes'}))$("#"+i).value=l[k]??''}else{$('#fDue').value=today();$('#fPriority').value='Hoch';$('#fStatus').value='neu'}hint();open('leadDialog')}
function hint(){const q=qual($('#fTpv').value);$('#qualificationHint').className='qual-box '+q.c;$('#qualificationHint').innerHTML='<b>Interne Qualifizierung: '+q.l+'</b><br>'+q.x+'. '+(+$('#fTpv').value>=5000?'Internes Vertriebsziel erreicht.':'Unter €5.000 TPV: intern niedriger priorisieren.')}$('#fTpv').oninput=hint;
$('#leadForm').onsubmit=e=>{e.preventDefault();const company=$('#fCompany').value.trim();if(!company)return toast('Firma fehlt');const tpv=+$('#fTpv').value||0,q=qual(tpv),d={id:$('#leadId').value||uid(),company,industry:$('#fIndustry').value,status:$('#fStatus').value,contact:$('#fContact').value.trim(),phone:$('#fPhone').value.trim(),email:$('#fEmail').value.trim(),address:$('#fAddress').value.trim(),tpv,qualification:q.l,qualified:tpv>=5000,provider:$('#fProvider').value.trim(),terminal:$('#fTerminal').value.trim(),product:$('#fProduct').value,priority:$('#fPriority').value,need:$('#fNeed').value.trim(),next:$('#fNext').value.trim(),due:$('#fDue').value,notes:$('#fNotes').value.trim(),updatedAt:new Date().toISOString()};const i=S.leads.findIndex(x=>x.id===d.id);i>=0?S.leads[i]={...S.leads[i],...d}:S.leads.unshift(d);save();close('leadDialog');render();toast('Lead gespeichert')};
function card(l){const q=qual(l.tpv);return `<article class="card lead-card"><div class="row"><div><h3>${esc(l.company)}</h3><div class="meta">${esc(l.industry||'')} · ${esc(l.address||'Keine Adresse')}</div>${l.contact?`<div class="meta">👤 ${esc(l.contact)}${l.phone?' · '+esc(l.phone):''}</div>`:''}</div><span class="badge">${esc(sl(l.status))}</span></div><div class="chips"><span class="chip ${q.l==='A'||q.l==='B'?'good':q.l==='C'?'warn':'bad'}">TPV ${money(l.tpv)} · ${q.l}</span><span class="chip">${esc(l.priority||'Mittel')} Priorität</span>${l.product?`<span class="chip">${esc(l.product)}</span>`:''}</div>${l.next||l.due?`<div class="meta" style="margin-top:9px">↗ ${esc(l.next||'Follow-up')} · ${esc(l.due||'')}</div>`:''}<div class="lead-actions">${l.phone?`<button data-phone="${esc(l.phone)}">☎️ Anrufen</button>`:''}${l.address?`<button data-map="${encodeURIComponent(l.address)}">🧭 Maps</button>`:''}<button data-edit="${l.id}">✏️ Bearbeiten</button><button data-visit="${l.id}">📝 Besuch</button><button data-quote="${l.id}">💼 Angebot</button><button data-del="${l.id}">🗑️</button></div></article>`}
function leads(){const s=($('#leadSearch').value||'').toLowerCase(),a=S.leads.filter(l=>lf==='all'||l.status===lf).filter(l=>[l.company,l.address,l.contact,l.phone,l.industry,l.provider].join(' ').toLowerCase().includes(s));$('#leadList').innerHTML=a.map(card).join('')||'<div class="empty">Keine Leads gefunden.</div>'}
$('#leadSearch').oninput=leads;$$('[data-filter]').forEach(b=>b.onclick=()=>{lf=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');leads()});
$('#leadList').onclick=e=>{let id=e.target.closest('[data-edit]')?.dataset.edit;if(id)return lead(id);id=e.target.closest('[data-del]')?.dataset.del;if(id){if(confirm('Diesen Lead wirklich löschen?')){S.leads=S.leads.filter(x=>x.id!==id);save();render()};return}id=e.target.closest('[data-visit]')?.dataset.visit;if(id)return visit(id);id=e.target.closest('[data-quote]')?.dataset.quote;if(id)return quote(null,id);const p=e.target.closest('[data-phone]')?.dataset.phone;if(p)location.href='tel:'+p;const m=e.target.closest('[data-map]')?.dataset.map;if(m)window.open('https://www.google.com/maps/search/?api=1&query='+m,'_blank')};
function visit(id){const l=S.leads.find(x=>x.id===id);$('#visitLead').value=id;$('#visitTitle').textContent='Besuch · '+l.company;$('#vDate').value=today();$('#vNote').value='';open('visitDialog')}
$('#visitForm').onsubmit=e=>{e.preventDefault();const l=S.leads.find(x=>x.id===$('#visitLead').value);l.lastVisit=$('#vDate').value;l.notes=$('#vNote').value.trim();if(l.status==='neu')l.status='kontaktiert';l.updatedAt=new Date().toISOString();if($('#vNext').value.trim()){S.tasks.unshift({id:uid(),title:$('#vNext').value.trim(),due:$('#vDue').value||today(),leadId:l.id,note:'Nach Besuch',done:false})}save();close('visitDialog');render();toast('Besuch gespeichert')};
function task(){ $('#taskForm').reset();$('#tDue').value=today();$('#tLead').innerHTML='<option value="">Ohne Lead</option>'+S.leads.map(l=>`<option value="${l.id}">${esc(l.company)}</option>`).join('');open('taskDialog') }
$('#taskForm').onsubmit=e=>{e.preventDefault();S.tasks.unshift({id:uid(),title:$('#tTitle').value.trim(),due:$('#tDue').value,leadId:$('#tLead').value,note:$('#tNote').value.trim(),done:false});save();close('taskDialog');render();toast('Task gespeichert')};
$$('[data-taskfilter]').forEach(b=>b.onclick=()=>{tf=b.dataset.taskfilter;$$('[data-taskfilter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tasks()});
function tasks(){const a=S.tasks.filter(t=>tf==='all'||tf==='open'&&!t.done||tf==='done'&&t.done||tf==='today'&&!t.done&&t.due===today()).sort((a,b)=>(a.due||'').localeCompare(b.due||''));$('#taskList').innerHTML=a.map(t=>{const l=S.leads.find(x=>x.id===t.leadId);return `<div class="card task ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} data-task="${t.id}"><div class="task-body"><b>${esc(t.title)}</b><div class="meta ${!t.done&&t.due<today()?'overdue':''}">${esc(t.due||'ohne Datum')}${l?' · '+esc(l.company):''}</div>${t.note?`<div class="meta">${esc(t.note)}</div>`:''}</div></div>`}).join('')||'<div class="empty">Keine Tasks in dieser Ansicht.</div>'}
$('#taskList').onchange=e=>{const id=e.target.dataset.task;if(id){const t=S.tasks.find(x=>x.id===id);t.done=e.target.checked;save();tasks();renderDash()}};
function renderDash(){const openLeads=S.leads.filter(l=>!['gewonnen','verloren'].includes(l.status)).length;$('#kLeads').textContent=openLeads;$('#kTasks').textContent=S.tasks.filter(t=>!t.done&&t.due<=today()).length;$('#kAppts').textContent=S.leads.filter(l=>l.status==='termin').length;$('#kWon').textContent=S.leads.filter(l=>l.status==='gewonnen').length;$('#kQuotes').textContent=S.quotes.filter(q=>q.status!=='accepted').length;const a=[...S.leads].filter(l=>!['gewonnen','verloren'].includes(l.status)).sort((x,y)=>(x.due||'9999').localeCompare(y.due||'9999')).slice(0,4);$('#dashboardTasks').innerHTML=a.map(l=>`<div class="card"><div class="row"><b>${esc(l.company)}</b><span class="badge">${esc(l.due||'')}</span></div><div class="meta">${esc(l.next||'Nächsten Kontakt festlegen')}</div></div>`).join('')||'<div class="empty">Noch keine offenen Leads.</div>';const b=[...S.leads].sort((x,y)=>(y.tpv||0)-(x.tpv||0))[0];$('#assistantCard').innerHTML=b?`<div class="row"><div><b>${esc(b.company)}</b><div class="meta">Größtes aktuelles TPV-Potenzial</div></div><span class="chip good">${money(b.tpv)}</span></div><p class="muted">${b.tpv>=5000?'Qualifiziert: Bedarf prüfen und Tarifvergleich durchführen.':'TPV unter internem Ziel: Potenzial verifizieren.'}</p><button class="secondary" data-edit="${b.id}">Lead öffnen</button>`:'<b>Bereit für den ersten Lead.</b><p class="muted">Erfasse einen Händler und der Sales Assistant priorisiert ihn automatisch.</p>'}
$('#assistantCard').onclick=e=>{const id=e.target.closest('[data-edit]')?.dataset.edit;if(id)lead(id)};
async function geo(q){const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=de&q='+encodeURIComponent(q));const a=await r.json();if(!a[0])throw 0;return{lat:+a[0].lat,lon:+a[0].lon,label:a[0].display_name}}
const dist=(a,b)=>{const R=6371,r=x=>x*Math.PI/180,dlat=r(b.lat-a.lat),dlon=r(b.lon-a.lon),x=Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
async function coords(l){if(l.lat)return{lat:+l.lat,lon:+l.lon};try{return await geo(l.address)}catch{return null}}
async function makeRoute(){if(!area)return;const rad=+$('#areaRadius').value||5,a=[];for(const l of S.leads){if(!l.address)continue;const c=await coords(l);if(c&&dist(area,c)<=rad)a.push({...l,lat:c.lat,lon:c.lon})}a.sort((x,y)=>dist(area,x)-dist(area,y));route=a;$('#routeCount').textContent=a.length;$('#routeList').innerHTML=a.map((l,i)=>`<div class="route-item"><b>${i+1}. ${esc(l.company)}</b><span>${dist(area,l).toFixed(1)} km</span></div>`).join('')||'<div class="empty">Keine bestehenden Leads im Radius.</div>';$('#openRoute').disabled=!a.length;$('#areaStatus').textContent=a.length+' Leads im Gebiet.';}
async function prospects(){if(!area)return;$('#prospectList').innerHTML='<div class="muted">Unternehmen werden gesucht …</div>';try{const q=encodeURIComponent('shop OR kiosk OR cafe OR restaurant OR bakery OR hairdresser OR retail');const u=`https://overpass-api.de/api/interpreter?data=[out:json][timeout:20];(nwr["shop"](around:${(+$('#areaRadius').value||5)*1000},${area.lat},${area.lon});nwr["amenity"~"cafe|restaurant"](around:${(+$('#areaRadius').value||5)*1000},${area.lat},${area.lon});nwr["shop"="convenience"](around:${(+$('#areaRadius').value||5)*1000},${area.lat},${area.lon}););out center tags 80;`;const r=await fetch(u);const j=await r.json();const arr=j.elements.filter(x=>x.tags?.name).slice(0,30).map(x=>({name:x.tags.name,address:[x.tags['addr:street'],x.tags['addr:housenumber'],x.tags['addr:postcode'],x.tags['addr:city']].filter(Boolean).join(' '),lat:x.lat??x.center?.lat,lon:x.lon??x.center?.lon}));$('#prospectList').innerHTML=arr.map(p=>`<div class="prospect"><div><b>${esc(p.name)}</b><div class="meta">${esc(p.address||'Adresse nicht angegeben')}</div></div><button class="secondary" data-prospect="${encodeURIComponent(JSON.stringify(p))}">＋ Lead</button></div>`).join('')||'<div class="empty">Keine Treffer im öffentlichen Datenbestand.</div>'}catch{$('#prospectList').innerHTML='<div class="empty">Gebietssuche derzeit nicht verfügbar.</div>'}}
$('#searchArea').onclick=async()=>{const q=$('#areaQuery').value.trim();if(!q)return toast('PLZ oder Ort eingeben');$('#areaStatus').textContent='Gebiet wird ermittelt …';try{area=await geo(q);$('#areaStatus').textContent=area.label;await makeRoute();await prospects()}catch{$('#areaStatus').textContent='Gebiet nicht gefunden';toast('Ort/PLZ nicht gefunden')}};
$('#useLocation').onclick=()=>navigator.geolocation?.getCurrentPosition(async p=>{area={lat:p.coords.latitude,lon:p.coords.longitude,label:'Mein Standort'};$('#areaStatus').textContent='Mein Standort';await makeRoute();await prospects()},()=>toast('Standortzugriff nicht möglich'));
$('#openRoute').onclick=()=>{if(!route.length)return;const pts=route.map(x=>`${x.lat},${x.lon}`);window.open('https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(`${area.lat},${area.lon}`)+'&destination='+encodeURIComponent(pts.at(-1))+'&waypoints='+encodeURIComponent(pts.slice(0,-1).join('|'))+'&travelmode=driving','_blank')};
$('#prospectList').onclick=e=>{const b=e.target.closest('[data-prospect]');if(!b)return;const p=JSON.parse(decodeURIComponent(b.dataset.prospect));$('#leadForm').reset();$('#leadId').value='';$('#leadDialogTitle').textContent='Neuer Lead aus Gebiet';$('#fCompany').value=p.name;$('#fAddress').value=p.address||'';$('#fDue').value=today();$('#fStatus').value='neu';$('#fPriority').value='Mittel';hint();open('leadDialog')};
function pricing(){ $('#pTpv').value=5000;calcPricing();open('pricingDialog') }
function calcPricing(){const tpv=+$('#pTpv').value||0,rate=+$('#pCurrentRate').value||0,fixed=+$('#pCurrentFixed').value||0,current=tpv*rate/100+fixed,payg=tpv*0.0139,plus=tpv*0.0079+19;$('#pricingResult').innerHTML=`<div class="result"><b>Aktuell</b><strong>${money(current)}/Monat</strong><small>nach deinen Eingaben</small></div><div class="result"><b>SumUp umsatzbasiert</b><strong>${money(payg)}/Monat</strong><small>1,39% auf Kartenzahlungen · 0 € Monatsgebühr</small></div><div class="result"><b>SumUp Zahlungen Plus</b><strong>${money(plus)}/Monat</strong><small>0,79% auf berechtigte EEA-Verbraucherkarten · 19 € Monatsgebühr</small></div><div class="qual-box qual-C"><b>Sales Assistant</b><br>Empfehlung anhand der Eingaben und Kartenmischung prüfen. Kundenseitig keine Provision anzeigen.</div>`}
$('#pTpv').oninput=calcPricing;$('#pCurrentRate').oninput=calcPricing;$('#pCurrentFixed').oninput=calcPricing;
function commission(){calcCommission();open('commissionDialog')}
function calcCommission(){const tpv=+$('#cTpv').value||0,hw=+$('#cHardware').value||0,sw=+$('#cSoftware').value||0,activation=tpv>=500?200:0,pay=(tpv*0.007*12)*0.5,topup30=Math.max(0,pay-activation),hardware=hw*0.5,software=sw*12*0.5,bonus=(+$('#cContracts').value?100:0)+(+$('#cPos').value?100:0)+(+$('#cChampion').value?100:0)+(+$('#cMaster').value?100:0),total=activation+topup30+hardware+software+bonus;$('#commissionResult').innerHTML=`<div class="result"><b>Aktivierung</b><strong>${money(activation)}</strong></div><div class="result"><b>Payments Top-Up 30</b><strong>${money(topup30)}</strong><small>mit 0,7% angenommener Net Revenue Margin</small></div><div class="result"><b>Hardware</b><strong>${money(hardware)}</strong></div><div class="result"><b>Software</b><strong>${money(software)}</strong></div><div class="result"><b>Boni</b><strong>${money(bonus)}</strong></div><div class="result"><b>Interne Deal-Summe</b><strong>${money(total)}</strong><small>Nur intern · Vertragsbedingungen haben Vorrang</small></div>`}
$$('#commissionDialog input,#commissionDialog select').forEach(x=>x.oninput=calcCommission);
function quote(id=null,leadId=null){$('#quoteForm').reset();$('#qLead').innerHTML='<option value="">Ohne Lead</option>'+S.leads.map(l=>`<option value="${l.id}">${esc(l.company)}</option>`).join('');$('#quoteId').value=id||'';let q=id&&S.quotes.find(x=>x.id===id);if(!q&&leadId){const l=S.leads.find(x=>x.id===leadId);q={leadId:l.id,company:l.company,contact:l.contact,email:l.email,product:l.product||'Noch offen',price:0,note:l.need||''}}if(q){for(const [k,i] of Object.entries({leadId:'qLead',company:'qCompany',contact:'qContact',email:'qEmail',product:'qProduct',price:'qPrice',note:'qNote'}))$('#'+i).value=q[k]??''}$('#qDate').value=q?.date||today();open('quoteDialog')}
$('#quoteForm').onsubmit=e=>{e.preventDefault();const d={id:$('#quoteId').value||uid(),leadId:$('#qLead').value,company:$('#qCompany').value.trim(),contact:$('#qContact').value.trim(),email:$('#qEmail').value.trim(),product:$('#qProduct').value,note:$('#qNote').value.trim(),price:+$('#qPrice').value||0,date:$('#qDate').value,status:'draft'};const i=S.quotes.findIndex(x=>x.id===d.id);i>=0?S.quotes[i]={...S.quotes[i],...d}:S.quotes.unshift(d);const l=S.leads.find(x=>x.id===d.leadId);if(l&&l.status!=='gewonnen')l.status='angebot';save();close('quoteDialog');render();toast('Angebot gespeichert')};
function invoice(id=null){$('#invoiceForm').reset();$('#invoiceId').value=id||'';let x=id&&S.invoices.find(v=>v.id===id);if(x){for(const [k,i] of Object.entries({company:'iCompany',email:'iEmail',number:'iNumber',amount:'iAmount',note:'iNote'}))$('#'+i).value=x[k]??''}else $('#iNumber').value='NX-'+new Date().getFullYear()+'-'+String(S.invoices.length+1).padStart(4,'0');open('invoiceDialog')}
$('#invoiceForm').onsubmit=e=>{e.preventDefault();const d={id:$('#invoiceId').value||uid(),company:$('#iCompany').value.trim(),email:$('#iEmail').value.trim(),number:$('#iNumber').value.trim(),amount:+$('#iAmount').value||0,note:$('#iNote').value.trim(),date:today(),status:'draft'};const i=S.invoices.findIndex(x=>x.id===d.id);i>=0?S.invoices[i]=d:S.invoices.unshift(d);save();close('invoiceDialog');render();toast('Rechnung gespeichert')};
function docs(){const q=S.quotes;$('#quoteList').innerHTML=q.map(x=>`<div class="card"><div class="row"><div><b>Angebot · ${esc(x.company)}</b><div class="meta">${esc(x.product)} · ${money(x.price)} · ${esc(x.date)}</div></div><span class="badge">${esc(x.status)}</span></div><div class="lead-actions"><button data-mailquote="${x.id}">✉️ E-Mail</button><button data-editquote="${x.id}">✏️</button></div></div>`).join('')||'<div class="empty">Noch keine Angebote.</div>';$('#invoiceList').innerHTML=S.invoices.map(x=>`<div class="card"><div class="row"><div><b>${esc(x.number)} · ${esc(x.company)}</b><div class="meta">${money(x.amount)} · ${esc(x.date)}</div></div><span class="badge">${esc(x.status)}</span></div><div class="lead-actions"><button data-mailinvoice="${x.id}">✉️ E-Mail</button><button data-editinvoice="${x.id}">✏️</button></div></div>`).join('')||'<div class="empty">Noch keine Rechnungen.</div>'}
function mailQuote(id){const q=S.quotes.find(x=>x.id===id);const body=`Hallo ${q.contact||q.company},%0D%0A%0D%0Aanbei unser Angebot von neXaro Solutions.%0D%0A%0D%0AProdukt: ${q.product}%0D%0APreis: ${money(q.price)}%0D%0A${q.note||''}%0D%0A%0D%0AFreundliche Grüße`;location.href=`mailto:${encodeURIComponent(q.email||'')}?subject=${encodeURIComponent('Angebot neXaro Solutions – '+q.company)}&body=${body}`}
function mailInvoice(id){const x=S.invoices.find(v=>v.id===id);const body=`Hallo ${x.company},%0D%0A%0D%0Aanbei die Rechnungsdaten ${x.number}.%0D%0ABetrag: ${money(x.amount)}%0D%0A${x.note||''}%0D%0A%0D%0AFreundliche Grüße`;location.href=`mailto:${encodeURIComponent(x.email||'')}?subject=${encodeURIComponent('Rechnung '+x.number+' – neXaro Solutions')}&body=${body}`}
$('#quoteList').onclick=e=>{let id=e.target.closest('[data-editquote]')?.dataset.editquote;if(id)return quote(id);id=e.target.closest('[data-mailquote]')?.dataset.mailquote;if(id)mailQuote(id)};
$('#invoiceList').onclick=e=>{let id=e.target.closest('[data-editinvoice]')?.dataset.editinvoice;if(id)return invoice(id);id=e.target.closest('[data-mailinvoice]')?.dataset.mailinvoice;if(id)mailInvoice(id)};
function csv(){const rows=[['Firma','Branche','Status','Kontakt','Telefon','E-Mail','Adresse','TPV','Qualifizierung','Produkt','Priorität','Nächste Aktion','Nächster Kontakt'],...S.leads.map(l=>[l.company,l.industry,l.status,l.contact,l.phone,l.email,l.address,l.tpv,l.qualification,l.product,l.priority,l.next,l.due])];download('nexaro-leads.csv',rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n'),'text/csv;charset=utf-8')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#restoreInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{S={...base,...JSON.parse(r.result)};save();render();toast('Backup wiederhergestellt')}catch{toast('Backup ungültig')}};r.readAsText(f)};
function demo(){S.leads=[{id:uid(),company:'Demo Kiosk',industry:'Kiosk / Späti',status:'neu',contact:'Max Beispiel',phone:'01700000000',email:'',address:'10115 Berlin',tpv:8500,qualified:true,qualification:'C',product:'Solo',priority:'Hoch',need:'Hohe Kartengebühren',next:'Tarifvergleich',due:today(),notes:''},{id:uid(),company:'Demo Gastro',industry:'Gastronomie',status:'termin',contact:'Anna Beispiel',phone:'',email:'',address:'10117 Berlin',tpv:18000,qualified:true,qualification:'A',product:'Terminal',priority:'Hoch',need:'Schnelleres Terminal',next:'Termin vor Ort',due:today(),notes:''}];S.tasks=[{id:uid(),title:'Demo Gastro besuchen',due:today(),leadId:S.leads[1].id,note:'Termin',done:false}];save();render();toast('Demo-Daten angelegt')}
function render(){renderDash();leads();tasks();docs();if($('#more')?.classList.contains('active'))docs()}
render();
