const KEY="nexaro-crm-v1-final",Q=s=>document.querySelector(s),QA=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const uid=()=>crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2),today=()=>new Date().toISOString().slice(0,10);
const money=n=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n)||0);
const base={leads:[],tasks:[],settings:{}};let S=(()=>{try{return {...base,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return structuredClone(base)}})();
let lf="all",tf="open",area=null,route=[];const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const toast=m=>{let t=Q("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)};
const close=id=>Q("#"+id)?.close(),open=id=>Q("#"+id)?.showModal();
function qual(t){t=+t||0;return t>=15000?{l:"A",x:"Sehr starkes Potenzial",c:"qual-A"}:t>=10000?{l:"B",x:"Stark qualifiziert",c:"qual-B"}:t>=5000?{l:"C",x:"Qualifiziert",c:"qual-C"}:{l:"D",x:"Unter internem Vertriebsziel",c:"qual-D"}}
const sl=s=>({neu:"Neu",kontaktiert:"Kontaktiert",termin:"Termin",gewonnen:"Gewonnen",verloren:"Verloren"}[s]||s);

function nav(id){QA(".screen").forEach(x=>x.classList.toggle("active",x.id===id));QA("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.screen===id));window.scrollTo(0,0);render()}
QA("[data-screen]").forEach(b=>b.onclick=()=>nav(b.dataset.screen));
document.onclick=e=>{let c=e.target.closest("[data-close]");if(c){close(c.dataset.close);return}let a=e.target.closest("[data-action]")?.dataset.action;if(a)act(a)};

function act(a){if(a==="new-lead")return lead();if(a==="new-task")return task();if(a==="pricing")return pricing();if(a==="commission")return commission();if(a==="export-csv")return csv();if(a==="backup")return download("nexaro-crm-backup.json",JSON.stringify(S,null,2),"application/json");if(a==="restore")return Q("#restoreInput").click();if(a==="demo")return demo();if(a==="clear"&&confirm("Alle lokalen CRM-Daten löschen?")){S=structuredClone(base);save();render();toast("CRM gelöscht")}}
function lead(id=null){Q("#leadForm").reset();Q("#leadId").value=id||"";Q("#leadDialogTitle").textContent=id?"Lead bearbeiten":"Neuer Lead";let l=id&&S.leads.find(x=>x.id===id);if(l){for(let [k,id2] of [["company","fCompany"],["industry","fIndustry"],["status","fStatus"],["contact","fContact"],["phone","fPhone"],["email","fEmail"],["address","fAddress"],["tpv","fTpv"],["provider","fProvider"],["terminal","fTerminal"],["product","fProduct"],["priority","fPriority"],["need","fNeed"],["next","fNext"],["due","fDue"],["notes","fNotes"]])Q("#"+id2).value=l[k]??""}else{Q("#fDue").value=today();Q("#fPriority").value="Hoch";Q("#fStatus").value="neu"}hint();open("leadDialog")}
function hint(){let q=qual(Q("#fTpv").value);Q("#qualificationHint").className="qual-box "+q.c;Q("#qualificationHint").innerHTML="<b>Interne Qualifizierung: "+q.l+"</b><br>"+q.x+". "+(+Q("#fTpv").value>=5000?"Internes Vertriebsziel erreicht.":"Unter €5.000 TPV: intern niedriger priorisieren.")}
Q("#fTpv").oninput=hint;
Q("#leadForm").onsubmit=e=>{e.preventDefault();let company=Q("#fCompany").value.trim();if(!company)return toast("Firma fehlt");let tpv=+Q("#fTpv").value||0,q=qual(tpv),d={id:Q("#leadId").value||uid(),company,industry:Q("#fIndustry").value,status:Q("#fStatus").value,contact:Q("#fContact").value.trim(),phone:Q("#fPhone").value.trim(),email:Q("#fEmail").value.trim(),address:Q("#fAddress").value.trim(),tpv,qualification:q.l,qualified:tpv>=5000,provider:Q("#fProvider").value.trim(),terminal:Q("#fTerminal").value.trim(),product:Q("#fProduct").value,priority:Q("#fPriority").value,need:Q("#fNeed").value.trim(),next:Q("#fNext").value.trim(),due:Q("#fDue").value,notes:Q("#fNotes").value.trim(),updatedAt:new Date().toISOString()};let i=S.leads.findIndex(x=>x.id===d.id);i>=0?S.leads[i]={...S.leads[i],...d}:S.leads.unshift(d);save();close("leadDialog");render();toast("Lead gespeichert")};

function card(l){let q=qual(l.tpv);return `<article class="card lead-card"><div class="row"><div><h3>${esc(l.company)}</h3><div class="meta">${esc(l.industry||"")} · ${esc(l.address||"Keine Adresse")}</div></div><span class="badge">${esc(sl(l.status))}</span></div><div class="chips"><span class="chip ${q.l==="A"||q.l==="B"?"good":q.l==="C"?"warn":"bad"}">TPV ${money(l.tpv)} · ${q.l}</span><span class="chip">${esc(l.priority||"Mittel")} Priorität</span>${l.product?`<span class="chip">${esc(l.product)}</span>`:""}</div>${l.next||l.due?`<div class="meta" style="margin-top:9px">↗ ${esc(l.next||"Follow-up")} · ${esc(l.due||"")}</div>`:""}<div class="lead-actions">${l.phone?`<button data-phone="${esc(l.phone)}">☎️ Anrufen</button>`:""}${l.address?`<button data-map="${encodeURIComponent(l.address)}">🧭 Maps</button>`:""}<button data-edit="${l.id}">✏️ Bearbeiten</button><button data-visit="${l.id}">📝 Besuch</button><button data-del="${l.id}">🗑️</button></div></article>`}
function leads(){let s=(Q("#leadSearch").value||"").toLowerCase(),a=S.leads.filter(l=>lf==="all"||l.status===lf).filter(l=>[l.company,l.address,l.contact,l.phone,l.industry].join(" ").toLowerCase().includes(s));Q("#leadList").innerHTML=a.map(card).join("")||'<div class="empty">Keine Leads gefunden.</div>'}
Q("#leadSearch").oninput=leads;QA("[data-filter]").forEach(b=>b.onclick=()=>{lf=b.dataset.filter;QA("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");leads()});
Q("#leadList").onclick=e=>{let id=e.target.closest("[data-edit]")?.dataset.edit;if(id)return lead(id);id=e.target.closest("[data-del]")?.dataset.del;if(id){if(confirm("Diesen Lead wirklich löschen?")){S.leads=S.leads.filter(x=>x.id!==id);save();render()};return}id=e.target.closest("[data-visit]")?.dataset.visit;if(id){let l=S.leads.find(x=>x.id===id),n=prompt("Besuchsnotiz für "+l.company,l.notes||"");if(n!==null){l.notes=n;l.lastVisit=today();if(l.status==="neu")l.status="kontaktiert";save();render();toast("Besuch gespeichert")}}let p=e.target.closest("[data-phone]")?.dataset.phone;if(p)location.href="tel:"+p;let m=e.target.closest("[data-map]")?.dataset.map;if(m)window.open("https://www.google.com/maps/search/?api=1&query="+m,"_blank")};

function task(){Q("#taskForm").reset();Q("#tDue").value=today();Q("#tLead").innerHTML='<option value="">Ohne Lead</option>'+S.leads.map(l=>`<option value="${l.id}">${esc(l.company)}</option>`).join("");open("taskDialog")}
Q("#taskForm").onsubmit=e=>{e.preventDefault();S.tasks.unshift({id:uid(),title:Q("#tTitle").value.trim(),due:Q("#tDue").value,leadId:Q("#tLead").value,note:Q("#tNote").value.trim(),done:false});save();close("taskDialog");render();toast("Task gespeichert")};
QA("[data-taskfilter]").forEach(b=>b.onclick=()=>{tf=b.dataset.taskfilter;QA("[data-taskfilter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");tasks()});
function tasks(){let a=S.tasks.filter(t=>tf==="all"||tf==="open"&&!t.done||tf==="done"&&t.done||tf==="today"&&!t.done&&t.due===today()).sort((a,b)=>(a.due||"").localeCompare(b.due||""));Q("#taskList").innerHTML=a.map(t=>{let l=S.leads.find(x=>x.id===t.leadId);return `<div class="card task ${t.done?"done":""}"><input type="checkbox" ${t.done?"checked":""} data-task="${t.id}"><div class="task-body"><div><b>${esc(t.title)}</b></div><div class="meta ${!t.done&&t.due<today()?"overdue":""}">${esc(t.due||"ohne Datum")}${l?" · "+esc(l.company):""}</div>${t.note?`<div class="meta">${esc(t.note)}</div>`:""}</div></div>`}).join("")||'<div class="empty">Keine Tasks in dieser Ansicht.</div>'}
Q("#taskList").onchange=e=>{let id=e.target.dataset.task;if(id){let t=S.tasks.find(x=>x.id===id);t.done=e.target.checked;save();tasks();renderDash()}};

function renderDash(){Q("#kLeads").textContent=S.leads.filter(l=>!["gewonnen","verloren"].includes(l.status)).length;Q("#kTasks").textContent=S.tasks.filter(t=>!t.done&&t.due<=today()).length;Q("#kAppts").textContent=S.leads.filter(l=>l.status==="termin").length;Q("#kWon").textContent=S.leads.filter(l=>l.status==="gewonnen").length;let a=[...S.leads].filter(l=>!["gewonnen","verloren"].includes(l.status)).sort((x,y)=>(x.due||"9999").localeCompare(y.due||"9999")).slice(0,4);Q("#dashboardTasks").innerHTML=a.map(l=>`<div class="card"><div class="row"><b>${esc(l.company)}</b><span class="badge">${esc(l.due||"")}</span></div><div class="meta">${esc(l.next||"Nächsten Kontakt festlegen")}</div></div>`).join("")||'<div class="empty">Noch keine offenen Leads.</div>';let b=[...S.leads].sort((x,y)=>(y.tpv||0)-(x.tpv||0))[0];Q("#assistantCard").innerHTML=b?`<div class="row"><div><b>${esc(b.company)}</b><div class="meta">Größtes aktuelles TPV-Potenzial</div></div><span class="chip good">${money(b.tpv)}</span></div><p class="muted">${b.tpv>=5000?"Qualifiziert: Bedarf und Tarifvergleich konkretisieren.":"TPV unter internem Ziel: Potenzial verifizieren."}</p><button class="secondary" data-edit="${b.id}">Lead öffnen</button>`:'<b>Bereit für den ersten Lead.</b><p class="muted">Erfasse einen Händler und der Sales Assistant priorisiert ihn automatisch.</p>'}
Q("#assistantCard").onclick=e=>{let id=e.target.closest("[data-edit]")?.dataset.edit;if(id)lead(id)};

async function geo(q){let r=await fetch("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=de&q="+encodeURIComponent(q));let a=await r.json();if(!a[0])throw 0;return{lat:+a[0].lat,lon:+a[0].lon,label:a[0].display_name}}
const dist=(a,b)=>{let R=6371,r=x=>x*Math.PI/180,dlat=r(b.lat-a.lat),dlon=r(b.lon-a.lon),x=Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
async function coords(l){if(l.lat)return{lat:+l.lat,lon:+l.lon};try{return await geo(l.address)}catch{return null}}
async function makeRoute(){if(!area)return;let rad=+Q("#areaRadius").value||5,a=[];for(let l of S.leads){if(!l.address)continue;let c=await coords(l);if(c&&dist(area,c)<=rad){if(!l.lat){l.lat=c.lat;l.lon=c.lon}a.push({...l,lat:c.lat,lon:c.lon});}}save();let left=[...a],p=area;route=[];while(left.length){let bi=0,bd=1e9;left.forEach((x,i)=>{let d=dist(p,x);if(d<bd){bd=d;bi=i}});let n=left.splice(bi,1)[0];n.rd=bd;route.push(n);p=n}renderRoute();toast(route.length+" Leads in Route")}
function renderRoute(){Q("#routeCount").textContent=route.length;Q("#routeList").innerHTML=route.map((l,i)=>`<div class="route-row"><div class="row"><b>${i+1}. ${esc(l.company)}</b><span class="meta">${l.rd?.toFixed(1)||""} km</span></div><div class="meta">${esc(l.address)}</div></div>`).join("")||'<div class="empty">Keine gespeicherten Leads im Radius.</div>';Q("#openRoute").disabled=!route.length}
Q("#useLocation").onclick=()=>navigator.geolocation?.getCurrentPosition(async p=>{area={lat:p.coords.latitude,lon:p.coords.longitude,label:"Mein Standort"};Q("#areaStatus").textContent="Standort aktiv.";await makeRoute();prospects()},()=>toast("Standortzugriff nicht erlaubt."));
Q("#searchArea").onclick=async()=>{let q=Q("#areaQuery").value.trim();if(!q)return toast("PLZ oder Ort eingeben");try{Q("#areaStatus").textContent="Gebiet wird ermittelt …";area=await geo(q);Q("#areaStatus").textContent=area.label;await makeRoute();prospects()}catch{toast("Gebiet nicht gefunden")}};
Q("#openRoute").onclick=()=>{let w=route.map(x=>encodeURIComponent(x.address)).join("|"),d=encodeURIComponent(route.at(-1).address),o=encodeURIComponent(`${area.lat},${area.lon}`);window.open("https://www.google.com/maps/dir/?api=1&origin="+o+"&destination="+d+"&waypoints="+w+"&travelmode=driving","_blank")};
async function prospects(){if(!area)return;let rad=Math.min(+Q("#areaRadius").value||5,20)*1000,q=`[out:json][timeout:20];(nwr["shop"](around:${rad},${area.lat},${area.lon});nwr["amenity"~"cafe|restaurant|fast_food|bar"](around:${rad},${area.lat},${area.lon});nwr["office"](around:${rad},${area.lat},${area.lon}););out center tags 80;`;Q("#prospectList").innerHTML='<div class="empty">Unternehmen werden gesucht …</div>';try{let r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",body:q}),d=await r.json(),a=d.elements.map(x=>{let t=x.tags||{},lat=x.lat??x.center?.lat,lon=x.lon??x.center?.lon;return{name:t.name||"",type:t.shop||t.amenity||t.office||"Unternehmen",address:[t["addr:street"],t["addr:housenumber"],t["addr:postcode"],t["addr:city"]].filter(Boolean).join(" "),lat,lon}}).filter(x=>x.name).sort((a,b)=>dist(area,a)-dist(area,b)).slice(0,30);Q("#prospectList").innerHTML=a.map(x=>`<div class="prospect"><div class="row"><b>${esc(x.name)}</b><span class="meta">${dist(area,x).toFixed(1)} km</span></div><div class="meta">${esc(x.type)}${x.address?" · "+esc(x.address):""}</div><button class="secondary" data-p="${encodeURIComponent(x.name+" "+x.address)}">🧭 Maps</button></div>`).join("")||'<div class="empty">Keine benannten Unternehmen gefunden.</div>'}catch{Q("#prospectList").innerHTML='<div class="empty">Die kostenfreie Gebietssuche ist gerade nicht erreichbar.</div>'}}
Q("#prospectList").onclick=e=>{let q=e.target.closest("[data-p]")?.dataset.p;if(q)window.open("https://www.google.com/maps/search/?api=1&query="+q,"_blank")};

function pricing(){open("pricingDialog");calcPrice()}QA(["#pTpv","#pCurrentRate","#pCurrentFixed"].join(",")).forEach(x=>x.oninput=calcPrice);
function calcPrice(){let t=+Q("#pTpv").value||0,r=+Q("#pCurrentRate").value||0,f=+Q("#pCurrentFixed").value||0,c=t*r/100+f,p=t*.0139,z=t*.0079+19,b=z<p?"Zahlungen Plus":"Umsatzbasiertes Zahlen";Q("#pricingResult").innerHTML=`<div class="result"><b>Aktuell</b><br>${money(c)}/Monat</div><div class="result"><b>Umsatzbasiert</b><br>${money(p)}/Monat</div><div class="result"><b>Zahlungen Plus</b><br>${money(z)}/Monat</div><div class="result"><b>Rechnerische Empfehlung</b><br>${b}</div>`}
function commission(){open("commissionDialog");calcCom()}QA(["#cTpv","#cHardware","#cSoftware","#cContracts","#cPos","#cChampion","#cMaster"].join(",")).forEach(x=>x.oninput=calcCom);
function calcCom(){let t=+Q("#cTpv").value||0,h=+Q("#cHardware").value||0,s=+Q("#cSoftware").value||0,a=t>=500?200:0,d=Math.max(0,t*.007*12*.5-a),e=Math.max(0,t*.007*12*.5-(a+d)),hw=h*.5,sw=s*12*.5,bon=+Q("#cContracts").value*100+ +Q("#cPos").value*100+ +Q("#cChampion").value*100+ +Q("#cMaster").value*100,total=a+d+e+hw+sw+bon,res=t*.007*.2;Q("#commissionResult").innerHTML=`<div class="result"><b>Sofortkomponente</b><br>${money(total)}</div><div class="result"><b>Residual</b><br>${money(res)}/Monat · ${money(res*24)} über 24 Monate</div><div class="result"><b>Bausteine</b><br>Aktivierung ${money(a)} · Tag 30 ${money(d)} · Tag 60 ${money(e)} · Hardware ${money(hw)} · Software ${money(sw)} · Boni ${money(bon)}</div>`}
function csv(){let c=["company","industry","status","contact","phone","email","address","tpv","qualification","qualified","provider","terminal","product","priority","need","next","due","notes"],rows=[c.join(";"),...S.leads.map(l=>c.map(k=>`"${String(l[k]??"").replaceAll('"','""')}"`).join(";"))];download("nexaro-leads.csv","\ufeff"+rows.join("\n"),"text/csv;charset=utf-8");toast("CSV exportiert")}
function download(n,t,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
Q("#restoreInput").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.leads)||!Array.isArray(x.tasks))throw 0;S=x;save();render();toast("Backup wiederhergestellt")}catch{alert("Ungültiges Backup.")}};r.readAsText(f);e.target.value=""};
function demo(){if(!confirm("Demo-Daten hinzufügen/ersetzen?"))return;let d=[["Späti am Markt","Kiosk / Späti","neu","10115 Berlin",6500,"Solo"],["Bäckerei Morgenrot","Bäckerei","kontaktiert","10999 Berlin",12000,"Terminal"],["Mode & Alltag","Einzelhandel","termin","03046 Cottbus",18000,"Kassensystem / POS"],["Friseur Studio","Friseur / Beauty","neu","14467 Potsdam",3500,"Tap to Pay"]];S.leads=d.map(x=>({id:uid(),company:x[0],industry:x[1],status:x[2],address:x[3],tpv:x[4],qualification:qual(x[4]).l,qualified:x[4]>=5000,product:x[5],priority:x[4]>=10000?"Hoch":x[4]>=5000?"Mittel":"Niedrig",next:"Nachfassen",due:today(),notes:""}));S.tasks=[{id:uid(),title:"Angebot nachfassen",due:today(),leadId:S.leads[1].id,note:"Tarifvergleich vorbereiten",done:false},{id:uid(),title:"Termin vorbereiten",due:today(),leadId:S.leads[2].id,note:"POS-Bedarf klären",done:false}];save();render();toast("Demo-Daten geladen")}
function renderDash(){Q("#kLeads").textContent=S.leads.filter(l=>!["gewonnen","verloren"].includes(l.status)).length;Q("#kTasks").textContent=S.tasks.filter(t=>!t.done&&t.due<=today()).length;Q("#kAppts").textContent=S.leads.filter(l=>l.status==="termin").length;Q("#kWon").textContent=S.leads.filter(l=>l.status==="gewonnen").length;let a=S.leads.filter(l=>!["gewonnen","verloren"].includes(l.status)).sort((x,y)=>(x.due||"9999").localeCompare(y.due||"9999")).slice(0,4);Q("#dashboardTasks").innerHTML=a.map(l=>`<div class="card"><div class="row"><b>${esc(l.company)}</b><span class="badge">${esc(l.due||"")}</span></div><div class="meta">${esc(l.next||"Nächsten Kontakt festlegen")}</div></div>`).join("")||'<div class="empty">Noch keine offenen Leads.</div>';let b=[...S.leads].sort((x,y)=>(y.tpv||0)-(x.tpv||0))[0];Q("#assistantCard").innerHTML=b?`<div class="row"><div><b>${esc(b.company)}</b><div class="meta">Größtes aktuelles TPV-Potenzial</div></div><span class="chip good">${money(b.tpv)}</span></div><p class="muted">${b.tpv>=5000?"Qualifiziert: Bedarf und Tarifvergleich konkretisieren.":"TPV unter internem Ziel: Potenzial verifizieren."}</p><button class="secondary" data-edit="${b.id}">Lead öffnen</button>`:'<b>Bereit für den ersten Lead.</b><p class="muted">Erfasse einen Händler und der Sales Assistant priorisiert ihn automatisch.</p>'}
Q("#assistantCard").onclick=e=>{let id=e.target.closest("[data-edit]")?.dataset.edit;if(id)lead(id)};
function render(){renderDash();leads();tasks();renderRoute()}render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
